### ISSUE TITLE
Harvest not restoring berry properly after switch

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#500] opened 2020-04-26 06:42 UTC
> Eternity Today at 2:36 AM
> My Exeggutor harvested a Sitrus Berry at end of turn, I changed Pokemon and then the berry dissappeared once it went back
> End of combat: the berry is back lol
> 
> One Winged Angel With No Brim Today at 2:38 AM
> So it had a Sitrus Berry, you switched it out, it lost the Sitrus Berry the next time you opened the party menu in-battle?
> 
> Eternity Today at 2:39 AM
> Yeah
> I just tried in the next battle, it harvested the berry, switched to Politoed (holding Mystic Water), then Politoed healed with the berry lol

Hooray for issue #500 🥳

**Comment by FredrIQ** [comment] 2020-05-04 16:42
Cannot reproduce this.

**Comment by FredrIQ** [comment] 2023-03-11 11:27
Fixed in a semi-recent commit. There was a subtle memory corruption bug in the battle engine due to wCurPartyMon vs wCurBattleMon confusion.

**Closed by FredrIQ** 2023-03-11 11:27 UTC
Labels: battle engine, unconfirmed, abilities
