### ISSUE TITLE
[Debug Nightly] Crash During Lyra's Tutorial

### ISSUE THREAD

**Issue by Ravendwyr** [Rangi42/polishedcrystal#529] opened 2020-06-15 20:11 UTC
Good evening,

I broke Lyra's catching tutorial earlier by catching a Pokemon on Route 29 in Nuzlocke Mode prior to naming the rival (I used the debug tool in the radio to obtain the balls).  The game tried to catch a Pidgey but the box came up saying I've already caught a Pokemon on the route before resulting in a division by zero error message.

![image](https://user-images.githubusercontent.com/8914/84700862-d938ae80-af4b-11ea-8672-8295b712c2af.png)

I was able to reset the game however and saying no to her request works as she gives us the Pokeballs before leaving the route.

This was using the Nightly Debug release based on commit [bc5f9c8b9085814645d3f62ab82e54591406c5f3] in VBA-M 2.1.0.

I hope you are safe and well, and apologise for any inconvenience caused.

**Comment by itsdarsh** [comment] 2020-06-20 06:19
My fear is that this is an issue specific to VBA-M. Try using another emulator (gambatte, bgb, sameboy, mGBA would all be fine) and let me know if you're having an issue on those emulators.

**Comment by itsdarsh** [comment] 2020-06-20 06:48
Normally, issues involving the debug rom and issues involving VBA-M are considered `WONTFIX`. In this case however, the issue is trivial enough to trigger and trivial enough to fix that a patch has been made. Just be aware that issues with the aforementioned complications likely will not be addressed in the future.

**Closed** 2020-06-20 06:48 UTC
