### ISSUE TITLE
Move accuracy seems nonrandom

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#243] opened 2019-03-02 18:42 UTC
Odd Coward: "Couple things that might not be bugs: Paralyze seems to almost always result in "is fully paralyzed" Maybe I'm just unlucky but I got that 6 times in a row in nuzlocke, had to switch out because I couldn't do anything against the ghastly. Accuracy seems... broken? I lowed a enemy's accuracy to minimum with smokescreen, they hit me about 90% of the time (only 1 of their moves missed). Conversely, in the battle against pidgeotto with falkner, it tends to spam mud-slap. After the first mud-slap my accuracy seemed to have tanked, almost immediately."

**Comment by Monstarules** [comment] 2019-07-12 00:15
I was just browsing through the issues and saw this. This honestly sounds like a really bad case of RNG, and not a real issue.

Paralysis is based on what's essentially a coin flip. Flipping a coin 6 times could result in 6 heads 1 out of 64 times (1.56%), which is not all that impossible.

With accuracy, if a Pokemon is using a move with a base accuracy of "100", and has it's accuracy decreased by 6 stages, it wil still on average hit 1 out of 3 moves (33%). If your accuracy is decreased by 1 stage, you will hit 2 out of 3 move (66%).

Neither of these issues are implausible at all, and given his circumstances for making this report, I don't think this issue needs to be open. I will leave it to you to decide whether to close it or not.

**Comment by SadisticMystic** [comment] 2019-07-12 00:26
6 FPs in a row is really the equivalent of 12 straight heads on a coin, not just 6, which (assuming that was actually what they observed, and not an embellishment being passed on for dramatic effect) plunges the odds to 0.024%.

For absolutely *any* series of nominally random events with positive probability, you can say that's a greater-than-0 chance of them happening all in a row and that there therefore must be a "chance" that it's not a bug at all, the question is what you're willing to take as your threshold of unreasonably bad luck before it has an effect on your priors as to whether the game is accurately reflecting the ideal probabilities that events are supposed to have.

**Comment by Monstarules** [comment] 2019-07-12 00:43
My bad, 1/4 chance not 1/2.

Anyways, you bring in an additional good point. There are likely embellishments in the statements.

**Comment by aaaaaa123456789** [comment] 2019-07-12 00:57
If everyone in the world rolled five dice and drew five random cards out of a perfectly shuffled deck, on average 10 people in the world would get a royal flush on the cards and a 5-of-a-kind on the dice at the same time.

Low probabilities aren't that low when they apply to high-frequency events. 6 FPs in a row are very rare, but over 1,000 battles (lowball estimate for a full run of a game), the odds of that happening once in the run are about 5%.

**Comment by FredrIQ** [comment] 2019-12-01 18:38
This is assumed to be confirmation bias, given no other reports has been forthcoming.

**Closed by FredrIQ** 2019-12-01 18:38 UTC
Labels: battle engine, moves, unconfirmed
