### ISSUE TITLE
Alternate formes of pokemon learns moves of their base form when they're leveled up in the day care

### ISSUE THREAD

**Issue by nadhiralua123** [Rangi42/polishedcrystal#657] opened 2021-12-09 13:45 UTC
Alolan Vulpix learns moves of regular Vulpix's level-up learnset when taken out of the day care. It can't learn those moves otherwise (through TMs or relearner), only by leveling up in the daycare.

**Comment by itsdarsh** [comment] 2022-02-23 17:58
This does not seem to be an issue on 9bit.

**Comment by itsdarsh** [comment] 2022-02-23 18:11
I'm going to actually leave this open because after diving through the code there really hasn't been anything that changed in 9bit that would've modified the relevant functions to my knowledge, but after stepping through the process the code seems fine and I can't immediately tell where this could break.

**Comment by vulcandth** [comment] 2023-01-28 05:08
Confirmed this. You can't reproduce this if you simple deposit a mon and immediately withdraw it. The party slot the mon is withdrawing to must have a differnent form ID than the mon in the daycare in order for the bug to occur. Tested and verified this is fixed with #783

**Closed** 2023-01-31 05:18 UTC
Labels: unconfirmed
