### ISSUE TITLE
Trainer register tune still doesn't play

### ISSUE THREAD

**Issue by ruvaldak** [Rangi42/polishedcrystal#239] opened 2019-03-02 05:49 UTC
![polishedcrystal-3 0 0-beta-190301-233115](https://user-images.githubusercontent.com/15901769/53677855-718a2180-3c7c-11e9-8e60-3419fad4eda7.png)

The tune that usually plays when this message appears in vanilla crystal still doesn't ever activate. I am 1 commit behind (latest commit pushed was a645cea, I compiled right before that was pushed)

**Comment by ruvaldak** [comment] 2019-03-02 05:51
I am using faithful

**Comment by FredrIQ** [comment] 2019-03-02 10:18
Can't reproduce this on non-Faithful non-Nuzlocke.

**Comment by ruvaldak** [comment] 2019-03-02 10:28
I will check non faithful on my end. Been using gambatte as well, will check on bgb

**Comment by FredrIQ** [comment] 2019-03-02 10:29
Where did you reproduce this?

**Comment by FredrIQ** [comment] 2019-03-02 10:36
Fixed in 4925057. Apparently only happened in Instant Text

**Closed by FredrIQ** 2019-03-02 10:36 UTC
Labels: cosmetic

**Comment by ruvaldak** [comment] 2019-03-02 10:38
ah, didn't realize instant text was causing the problem
